# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add1_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Form0(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(450, 200)
        self.frame = QtWidgets.QFrame(widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 201))
        self.frame.setStyleSheet("background-color: rgb(246, 247, 250);\n"
"color: rgb(110, 55, 238);\n"
"font: 16pt \".AppleSystemUIFont\";\n"
"color: rgb(139, 140, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 19, 451, 41))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_next = QtWidgets.QPushButton(self.frame)
        self.pushButton_next.setGeometry(QtCore.QRect(310, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_next.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.07, y1:0.227364, x2:0.895, y2:0.847, stop:0 rgba(110, 55, 238, 255), stop:0.487562 rgba(138, 110, 215, 255), stop:1 rgba(147, 134, 190, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius: 14px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_next.setObjectName("pushButton_next")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(75, 80, 300, 25))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("font: 12pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_2.setText(_translate("widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Select what type of question you want to add</span></p></body></html>"))
        self.pushButton_next.setText(_translate("widget", "Next"))
        self.comboBox.setItemText(0, _translate("widget", "Text answer"))
        self.comboBox.setItemText(1, _translate("widget", "True/False"))
        self.comboBox.setItemText(2, _translate("widget", "With answer options"))
        self.comboBox.setItemText(3, _translate("widget", "Flags"))
        self.comboBox.setItemText(4, _translate("widget", "Linear scale"))
        self.comboBox.setItemText(5, _translate("widget", "Table with answer options"))
        self.comboBox.setItemText(6, _translate("widget", "Grid of flags"))
