# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Form7(object):
    def setupUi(self, Warning):
        Warning.setObjectName("Warning")
        Warning.resize(450, 200)
        self.frame = QtWidgets.QFrame(Warning)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 201))
        self.frame.setStyleSheet("background-color: rgb(246, 247, 250);\n"
"color: rgb(110, 55, 238);\n"
"font: 16pt \".AppleSystemUIFont\";\n"
"color: rgb(139, 140, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(110, 55, 238);\n"
"font: 14pt \"Arial\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.07, y1:0.227364, x2:0.895, y2:0.847, stop:0 rgba(110, 55, 238, 255), stop:0.487562 rgba(138, 110, 215, 255), stop:1 rgba(147, 134, 190, 255));\n"
"border-radius: 18px;\n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(300, 70, 81, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 71, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(110, 55, 238);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(90, 60, 95, 20))
        self.radioButton.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(90, 100, 95, 20))
        self.radioButton_3.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_3.setObjectName("radioButton_3")

        self.retranslateUi(Warning)
        QtCore.QMetaObject.connectSlotsByName(Warning)

    def retranslateUi(self, Warning):
        _translate = QtCore.QCoreApplication.translate
        Warning.setWindowTitle(_translate("Warning", "Form"))
        self.label.setText(_translate("Warning", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Enter borders:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Warning", "OK"))
        self.lineEdit.setText(_translate("Warning", "0"))
        self.label_2.setText(_translate("Warning", "<html><head/><body><p><span style=\" font-size:12pt;\">than</span></p></body></html>"))
        self.radioButton.setText(_translate("Warning", "more"))
        self.radioButton_3.setText(_translate("Warning", "less"))
